### ISSUE TITLE
Warning: AES handshake failed

### ISSUE THREAD

**Issue by crabmanX** [Homegear/Homegear#286]
I am running homegear (version 0.6.20-987) on an rpi (192.168.1.31) with HM-MOD-RPI-PCB module and homeassistant (version 0.43.2) on my NAS (192.168.1.23), which uses pyhomematic to connect to homegear.
After a few days, i see these messages in my logs:

homegear.err

```
04/28/17 11:23:05.086 Module HomeMatic BidCoS: HM-MOD-RPI-PCB "My-HM-MOD-RPI-PCB": Warning: AES handshake failed for packet: 0D3EA6104DEEB9FD4A7D06010000F2
Removing server "homeassistant-wireless". Server has to send "init" again.
```

homegear.log
```
04/28/17 11:23:05.085 Module HomeMatic BidCoS: HM-MOD-RPI-PCB "My-HM-MOD-RPI-PCB": Warning: AES handshake failed for packet: 0D3EA6104DEEB9FD4A7D06010000F2
04/28/17 11:23:05.086 RPC client: Info: Calling RPC method "error" on server 192.168.1.23.
```

i filed a bug for pyhomematic (https://github.com/danielperna84/pyhomematic/issues/66) where i was asked to report the problem here, too.

**Comment by danielperna84** [comment]
I guess the actual questions here are:

1. Why does this error (AES handshake) happen?
2. Is dropping the XML-RPC connection generally the right thing to do if this error happens?
3. Are there possibilities to handle the dropped connection besides reacting on the error-method called via XML-RPC?
4. Would it be possible to have a static error code for dropped connections so the other side knows for sure that it has to send the init again?

**Comment by hfedcba** [comment]
@crabmanX: Could you send me more log lines (+- 20) around the error message? Homegear does not drop the connection because the AES handshake fails - at least there is no direct connection. There has to be another or indirect reason.

@danielperna84:

1. There can be many reasons. The most common cause are connection problems. Normally the error can be ignored. It is logged to be able to detect hacking attempts.
2. No, the connection shouldn't be dropped.
3. Yes, either through TCP keep alives (the connection really is closed, so this is detected by them) or by calling "ClientServerInitialized()" (see: https://ref.homegear.eu/rpc.html#clientServerInitialized)
4. It would be possible. But how is the other side supposed to receive the error message if the connection is dropped?

Cheers,

Sathya

**Comment by crabmanX** [comment]
@hfedcba 

sure, these are the logfiles i uploaded to the pyhomatic bug. I just removed the link because the probably contain sensitive info.

[homematic.logs.zip](https://github.com/Homegear/Homegear/files/966078/homematic.logs.zip)

**Comment by danielperna84** [comment]
3. Sadly the CCU doesn't seem to have such a clientServerInitialized method. Is there a RPC method that exists on both CCU and Homegear, but Homegear responds in a way that I programmatically can tell Homegear is used and not the CCU? Based on that I could use different methods depending on the backend. In the end both systems need to be supported. I could also just call a Homegear specific method and catch the exception if it's a CCU we're talking to. But catching the exception seem a little unsexy. :D 
4. Indeed, haven't thought that through. I just saw the handshake error arriving at my library, but that apparantly happens before the connection is dropped.

**Comment by hfedcba** [comment]
3. There is also the method "ping", which sends a "pong" to all event servers. This method is also supported by the CCU. The method works asynchronously though, which makes the usage a little more complicated. There are multiple ways to detect Homegear. I think OpenHAB calls "getVersion()", which returns something like "Homegear 0.6.20". Or "system.listMethods()" could be called and searched for Homegear specific methods. The latter method is supported by the CCU and by Homegear.
4. It might be possible the call to "error()" is the problem. How does the response to the method call look like? I already saw in the log that the call to "error()" after the handshake failure is the only one in the entire log file. So the call to this method might be the cause for the disruption. And if there is a response, Homegear doesn't understand, the connection indeed is closed.

**Comment by hfedcba** [comment]
I don't think the AES error has anything to do with the connection disruption. The handshake error occurs at 11:23. The connection is still alive after that until 12:03. At 12:03 the connection times out:

`04/28/17 12:03:06.697 RPC client: Info: Reading from RPC server timed out. Server: 192.168.1.23`

I very strongly think that's when Homegear disconnects the client and the error is written into the error log. Sadly I'm not logging the time information. I just changed that and the time information is logged starting with the next nightly.

@crabmanX: Could you add the following to the end of the file "/etc/homegear/rpcclients.conf"

```
[homeassistant]
hostname = 192.168.1.23
retries = 10
```

Does that maybe solve the problem?

**Comment by crabmanX** [comment]
@danielperna84 i set retries to 10, but it will take about a week until i can be sure if it worked. I will get back to you then.

**Comment by danielperna84** [comment]
3. Ok, the `getVersion()` seems to be a good solution. The CCU responds with just a version. So looking if the string contains Homegear will do the job.
4. Currently, calling the method via Python, it returns `True`. So a boolean is returned instead of the `void` mentioned in the Homegear [API reference](https://www.homegear.eu/index.php/Error#Return_value). I'll change that in pyhomematic. Is there a reason why anything but void should make the connection drop? Thinking about stability I assume accepting any response and just discarding it would mitigate possible errors.

**Comment by hfedcba** [comment]
4. The returned type doesn't matter as long as there is a response - so that's not a reason for a drop of connection. But as already stated, I don't think that's the problem. Let's see if the increased retry count solves the problem.

**Comment by crabmanX** [comment]
it happened again, this time with the 

```
[homeassistant]
hostname = 192.168.1.23
retries = 10
```

lines in rpcservers.conf.

The logs are attached. I filtered the homematic logs with 
`grep homematic home-assistant.log | grep -v websocket_api > home-assistant.log.filt`

[homematic.zip](https://github.com/Homegear/Homegear/files/970147/homematic.zip)

**Comment by danielperna84** [comment]
Can you tell me where in the log I have to look? The only error I see in homegear.log is at 23:07:16, which according to home-assistant.log is when you have restarted Home Assistant. The current pyhomematic does not de-init when shutting down, so in that case it's correct that Homegear reports that error. It should still work though since Home-Assistant is setting up a fresh instance of pyhomematic when restarting.

**Comment by crabmanX** [comment]
sorry, should have mentioned that. The last time HA logged a homematic value was 00:09:27 but i couldnt find anything in the HA logs around this time. I am going to upgrade homegear to the nighly version later today so we have timestamps in the error log as well.

**Comment by danielperna84** [comment]
Since the issue may indeed be on the HASS side I've posted my answer in your orginial issue for pyhomematic. Let's wait and see if the timestamps in the Homegear logs may give us a hint what the actual problem could be.

**Comment by hfedcba** [comment]
I agree with @danielperna84 that the problem probably is caused by a high system load or connection problems. The log again shows the connection timing out, meaning there was no response in time. The settings I posted need to be placed in "rpcclients.conf" not "rpcservers.conf"! Otherwise they won't work ;-). I just tested the setting here again, it works. But: You also need to set `forceSSL = false` which is `true` by default (in the next nightly not necessary anymore). The reason is that "rpcclients.conf" was meant to configure secure connections from Homegear to clients. I now also added the possibility to set the connection timeout in "rpcclients.conf". The default currently is 15 seconds. In the next nightly you could also set this to 60 seconds (`timeout = 60000`). That could solve your problem. For reference again the recommended settings:

```
[homeassistant]
hostname = 192.168.1.23
retries = 10
timeout = 60000
```

**Comment by crabmanX** [comment]
@hfedcba Cool, thank you for adding the timeout option! @danielperna84 is probably right and the problem is caused by high CPU loads, so i closed this issue. Thanks again for your support!

**Comment by hfedcba** [comment]
@crabmanX: Please report, if it worked with timeout set! I'm curious myself if that solves the problem.

**Comment by crabmanX** [comment]
@hfedcba Increasing the timeout worked, problem solved!
