### ISSUE TITLE
MQTT - not useable naming of devices in MQTT packets

### ISSUE THREAD

**Issue by MaciejSzulc1** [Homegear/Homegear#292]
Hi 

I've been working on MQTT code to allow connection to IBM  Bluemix Watson IOT Platform. I've made some changes to MQTT connect/publish code and now the connection works as expected. Soon I will create a patch for master branch and publish it on git. 

But during my development I've found that the MQTT adapter is not really useable.
At this point the Homegear MQTT adapter emmits data with Homematic device identifier set as  peerId and channel (example: peerId=3, channel=1). This means that it is very hard to distinguish the device types in MQTT receiver, as the peerId is an numeric index of Homegear database and will change if we remove/discover the device in Homegear. All we got is: deviceId=3, channel=1 and the payload {"HUMIDITY":57,"TEMPERATURE":23.3}

I wonder if it would be possible to change this behaviour to include Homematic serial instead of deviceId (example: IEQ0053893). It would be best to have also the device type (example: HM-CC-TC)

I've looked into a Mqtt.cpp and it looks like the Mqtt::queueMessage method gets only a  numeric peerId and numeric channel, so the change needs to be done somewhere else. 
Unfortunatelly I can't find proper place.

Is there anyone who could help or just direct me where to look?

**Comment by hfedcba** [comment]
> Soon I will create a patch for master branch and publish it on git.

Please create the pull request with the dev branch ;-).

> and will change if we remove/discover the device in Homegear

You can set the old ID in this case.

> I wonder if it would be possible to change this behaviour to include Homematic serial instead of deviceId

This has been discussed a lot. That's not a good idea, because Homegear supports much more than HomeMatic and the serial number is not necessarily unique. The ID is.

> It would be best to have also the device type

That would theoretically be possible. But I think it's better to get all the meta information another way. Another user might need the room the device is assigned to or the category. To blow up every MQTT packet with static information would take up a lot of resources. That gets especially important when packets are sent with very short delays in between. So I would keep the static information to the information absolutely needed.

Maybe lets discuss this further in the forum (https://forum.homegear.eu) and tell me there, what you want to accomplish. Then I'm sure, we can find a good solution.

Cheers,

Sathya

**Comment by hfedcba** [comment]
Btw. thanks for making the changes for Watson IoT. In the settings file I'd suggest to keep the settings in a seperate section and double the keys needed for Watson IoT and other clients.

**Comment by MaciejSzulc1** [comment]
Hi 

While trying to upgrade my homegear I saw that You’ve commented out all my IBM Cloud patches. Is there something wrong with them? How can I help in order to enable this integration?

regards
Maciej
