### ISSUE TITLE
 possibility to set enchant directory @ configure ?

### ISSUE THREAD

**Issue by thelaoshi** [Homegear/Homegear#295]
Hi there,
Arch Linux just released enchant 2 in their package tree.

Thanks to the changes in enchant I cant compile Homegear anymore.
So I compiled enchant 1.6 from source and installed it under /usr/local. That helps to be able to compile php 7.2 again successfully (with --with-enchant=/usr/local)
But I have no idea how to do that with homegear? :-(

best regards,
Mike

**Comment by hfedcba** [comment]
Hey Mike,

Homegear doens't need enchant by itself. It is only linked against (in `src/Makefile.am`), because PHP needs it. If `libenchant.so` can be found in the library search paths, it should work. But it seems it doesn't? What's the exact error? Is `libenchant` in your library search path? If not, add the path to `/etc/ld.so.conf` and run `ldconfig`, then it should work. But I think the better solution is to use enchant 2. Doesn't PHP compile using it or where is the problem?

Cheers,

Sathya

**Comment by PatrickE94** [comment]
I worked around the problem by not compiling PHP with the static encahnt module. I.e. by adding shared to the enchant module. 
```
- --with-enchant=/usr/local 
+ --with-enchant=shared,/usr/local
```

Arch seems to prefer shared libraries, is there any explicit reason PHP is statically linked?

**Comment by hfedcba** [comment]
> Arch seems to prefer shared libraries, is there any explicit reason PHP is statically linked?

You can also dynamically link it. The reason is that no other program will use Homegear's PHP library, so there is no need to make it shared.

**Comment by thelaoshi** [comment]
The php enchant extension seems to not support enchant 2 yet. :-(

Does it have to be in the searchpath before the compiling starts or at runtime ? I dont have much knowledge about how shared libs etc work under linux :-D

**Comment by hfedcba** [comment]
> Does it have to be in the searchpath before the compiling starts or at runtime ?

Before you run "configure" and at runtime. Except you link it statically, then you don't need it at runtime. The other option would be to just omit Enchant. Homegear itself doesn't need it.

**Comment by thelaoshi** [comment]
setting the path in the ldconfig helped :-) homegear uses now the enchant lib under /usr/local. Missed that Arch normally doesnt look there for libs

**Comment by hfedcba** [comment]
ok :-). Can we close the issue then?
