### ISSUE TITLE
Extend event data to get info about the event source

### ISSUE THREAD

**Issue by chrwick** [Homegear/Homegear#298]
Hi @hfedcba ,

I am currently working on a virtual device which creates an automated Homematic<->KNX Gateway.
For the Homematic connection the new CCU2 module is used.

A homegear PHP helper script generates an XML file with KNX group addresses from existing Homematic peers which can be imported directly into ETS. The resulting ETS Project file is imported into Homegear again.

The virtual device script is responsible for sending value updates from HM peers to KNX peers (group of group addresses mapped to a single HM device with channels/variables) and vice versa.

**Problem description:**
A peer has received a new value from the interface. The gateway script finds the corresponding counterpart peer.
When calling "$hg->setValue()" on the counterpart peer, an event is generated for this counterpart peer which RECEIVES the new value.
The problem is that the event does NOT contain any meta information if the new value was generated internally by the script of received on the interface.
This causes a message loop and the event bus is flooded untill the event buffer is full.

This problem only occures for datapoints which are bidirectional (readable AND writable).
For unidirectional datapoints this is not an issue, since events for writable data points could simply be ignored (event fired after setValue() is called). 

**Possible solutions**

1. add an additional field in the event array which contains info about the event origin: Example: `["ORIGIN"] = <interface>` or `["ORIGIN"] = <script id> (or virtual device peer id)`
2. extend setValue() to include user-defined metadata which gets included in the event data. Setting metadata just for the peer is not enough, since the information is related to events.

UPDATE#1:
Problem is basically the same as [here](https://github.com/Homegear/homegear-nodes-core/tree/master/variable/variable-loop-prevention-group).

**Comment by chrwick** [comment]
I have analysed the code.
It seems that there are a couple of functions which are releated to events: e.g. raiseEvent(), raiseRPCEvent(), etc.
Unfortunately, the signature of those functions always look the same "peerId, channel, variableName, Value". 
In my option this would require to refactor all those functions to some struct eventArgs which should be passed around. In this way it would be easy to introduced additional fields for events as different locations.

**Comment by chrwick** [comment]
For now I have used a third possible solution.
This is would you are using for feedback loop prevention.

However, I think that it would be better extend the event data to get the source of the event.

The third solution using this refraction time looks like a workaround for me.
There is always the chance of loosing events originating from the real interface when received within the refraction time interval.

**Comment by hfedcba** [comment]
There is no real solution to the problem except the feedback loop prevention. The reason is that often when you set a value you immediately get back a feedback from the device setting the value again. So as it would work for some devices to analyze the origin, it won't work for all. This is a common problem and the reason for the feedback loop prevention in Node-BLUE. The only solution would be to seperate input and output variables, but the manufacturer needs to do that.

**Comment by nanosonde** [comment]
Ok, thanks for the comment.
I hope that by using a minimal refraction time the problem of possibly missing value updates from the interface can be neglected practically.

Do you have some statistics on how fast the event queue gets processed or how long it takes for packet to travel through Homegear?
From what I saw in the logs (homegear-scriptengine.log) it seems to be about 1-3ms.
So I would assume that I can safely reduce the refraction time to let say 20ms?!
I would like to make sure that fast things like pressing button are not causing any issues.

**Comment by hfedcba** [comment]
> I hope that by using a minimal refraction time the problem of possibly missing value updates from the interface can be neglected practically.

You normally don't miss anything, except you manually change values on two devices at the same time. An example with feedback loop prevention set to 5 seconds: You change a temperature on your wall thermostat. This is being transmitted to the valve drive. For HomeMatic for example the valve drive sends a response after about 3 seconds, which is ignored. Another command from the wall thermostat is not ignored, because you know, it is the same device sending again. This is how the feedback loop prevention in Node-BLUE works. We use it in a lot of different conditions often with more than 2 devices and it works perfectly.

**Comment by chrwick** [comment]
Looking [here](https://github.com/Homegear/homegear-nodes-core/blob/master/variable/variable-loop-prevention-group/MyNode.cpp#L115) again, I have not realized this expression in the if-clause 

` && parameters->at(0)->stringValue != _lastEventNode`.

In my current implementation I am basically inhibiting ALL peer events belonging to the same group, but that does not make sense. It is enough to only inhibit all OTHER peer events, but not the originating peer.

I will close this. Thanks for the explanations.
